"""Add source field to Article

Revision ID: 00e57c2afe7b
Revises:
Create Date: 2023-04-26 12:57:08.421752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e57c2afe7b'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.add_column('article', sa.Column('source', sa.String(length=255), nullable=True))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    # ### end Alembic commands ###
